[Setup]
; Application metadata
AppName=SEA Media Archiver
AppVersion=1.0.0
AppPublisher=SEA
; Default installation folder (Program Files)
DefaultDirName={autopf}\SEA Media Archiver
DefaultGroupName=SEA Media Archiver
; Output settings for the final installer
OutputDir=Output
OutputBaseFilename=SEA_Media_Archiver_Setup
Compression=lzma
SolidCompression=yes
; Use your custom icon for the installer and uninstaller
SetupIconFile=my_icon.ico
UninstallDisplayIcon={app}\SEA Media Archiver.exe
PrivilegesRequired=admin

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Grab the standalone executable generated by PyInstaller
Source: "dist\SEA Media Archiver.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Create Start Menu and Desktop shortcuts
Name: "{group}\SEA Media Archiver"; Filename: "{app}\SEA Media Archiver.exe"
Name: "{autodesktop}\SEA Media Archiver"; Filename: "{app}\SEA Media Archiver.exe"; Tasks: desktopicon

[Run]
; Option to launch the app immediately after installation finishes
Filename: "{app}\SEA Media Archiver.exe"; Description: "{cm:LaunchProgram,SEA Media Archiver}"; Flags: nowait postinstall skipifsilent